name: Update Odigos Dependencies

on:   
  repository_dispatch:
    types: [enterprise-dependencies-update]
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Print github.event Object
        run: |
          echo "${{ toJson(github.event) }}" > event.json
          cat event.json

      - name: Extract PR Creator
        id: pr_creator
        run: echo "::set-output name=pr_creator::${{ github.event.pull_request.user.login }}"

      - name: Get PR Creator and Branch Details
        id: pr_details
        run: |
          echo "::set-output name=creator::${{ github.event.pull_request.user.login }}"
          echo "::set-output name=base_branch::${{ github.event.pull_request.base.ref }}"
          echo "::set-output name=head_branch::${{ github.event.pull_request.head.ref }}"

      - name: Validate Branches
        if: ${{ github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'develop' }}
        run: echo "This PR is from 'develop' to 'main'"


      # - name: create dependencies update pr
      #   id: create_dependencies_update_pr
      #   run: |
      #     git checkout -b ${{ steps.github_preperation.outputs.branch_name }}
      #     git add .
      #     git commit -m "update Odigos dependencies"
      #     git push origin ${{ steps.github_preperation.outputs.branch_name }}

      #     PR_LINK=$(gh pr create \
      #       --title "chore: automatic dependencies syncer bot" \ 
      #       --body "Automated PR to update Odigos enterprise components after a dependency module merge.
      #         PR created by: @${{ github.event.client_payload.pr_creator }}"
      #       --base main \
      #       --head ${{ steps.github_preperation.outputs.branch_name }})
          
      #     # Extract PR number from PR_LINK
      #     PR_NUMBER=$(echo "$PR_LINK" | awk -F '/' '{print $NF}')